import { LightningElement, api } from 'lwc';

export default class QuotePdfsTab extends LightningElement {
    @api quoteId;

    columns = [
        { label: 'Document Name', fieldName: 'name', type: 'text' },
        { label: 'Generated By', fieldName: 'generatedBy', type: 'text' },
        { label: 'Date', fieldName: 'date', type: 'date' },
        { label: 'Status', fieldName: 'status', type: 'text' },
        {
            type: 'button-icon',
            typeAttributes: {
                iconName: 'utility:download',
                name: 'download',
                title: 'Download'
            }
        }
    ];

    pdfData = [
        { id: '1', name: 'Quote_v1.pdf', generatedBy: 'Current User', date: new Date().toISOString(), status: 'Complete' }
    ];

    handleRowAction(event) {
        // Implement row action e.g., download mock
    }
}
